---
swagger: "2.0"
info:
  description: "A REST service that allows to create read and update a virtual directory\n"
  version: "0.0.1"
  title: "Virtual Directory REST Service Using Swagger"
  contact:
    name: "Cloudmesh virtual directory REST service"
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /dirs:
    get:
      description: "Returns a list of all directories"
      operationId: "dirs_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "a list of Dirs"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Dir"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /dir/{dir_name}:
    get:
      description: "Returns a list of files in the directory dir_name"
      operationId: "get_dir_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "dir_name"
        in: "path"
        description: "name of the directory to fetch"
        required: true
        type: "string"
      responses:
        200:
          description: "A list of files"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/File"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    post:
      description: "create/update a directory with the directory name dir_name"
      operationId: "create_dir"
      produces:
      - "application/json"
      parameters:
      - name: "dir_name"
        in: "path"
        description: "name of the directory to be created"
        required: true
        type: "string"
      responses:
        201:
          description: "directory created/updated"
          schema:
            $ref: "#/definitions/Dir"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  File:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
      parent_directory:
        type: "string"
      endpoint:
        type: "string"
    example:
      endpoint: "endpoint"
      name: "name"
      parent_directory: "parent_directory"
  Dir:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
      parent_directory:
        type: "string"
      files:
        type: "array"
        items:
          $ref: "#/definitions/File"
    example:
      name: "name"
      parent_directory: "parent_directory"
      files:
      - endpoint: "endpoint"
        name: "name"
        parent_directory: "parent_directory"
      - endpoint: "endpoint"
        name: "name"
        parent_directory: "parent_directory"
